// Copyright 2025 Victor Palma <victor.palma@rackspace.com>
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cluster

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	sopsAgeSecretStepID = "reconcile-sops-age-secret"
	sopsAgeSecretName   = "sops-age"
	sopsAgeSecretKey    = "age.agekey"
)

// newSopsAgeSecretStep creates a bootstrap step that reconciles the sops-age
// Kubernetes Secret in the flux-system namespace. This secret holds the Age
// private key that Flux uses to decrypt SOPS-encrypted secrets at reconciliation
// time. The key is read from the local path generated by `opencenter cluster init`.
func newSopsAgeSecretStep(sopsKeyPath, kubeconfigPath string, runner lifecycleCommandRunner) bootstrapStep {
	return bootstrapStep{
		ID:          sopsAgeSecretStepID,
		Description: "Reconcile SOPS Age decryption key for Flux",
		Plan: BootstrapPlanStep{
			ID:         sopsAgeSecretStepID,
			Action:     "Reconcile the sops-age Secret in flux-system",
			WorkingDir: "",
			Commands: []BootstrapPlanCommand{
				commandPlan("kubectl", "--kubeconfig", kubeconfigPath, "-n", fluxSystemNamespace, "create", "secret", "generic", sopsAgeSecretName, "--from-file="+sopsAgeSecretKey+"=<age-key-path>", "--dry-run=client", "-o", "yaml"),
				commandPlan("kubectl", "--kubeconfig", kubeconfigPath, "apply", "-f", "<temporary-secret-manifest>"),
			},
			Reads:  []string{sopsKeyPath, kubeconfigPath},
			Writes: []string{fmt.Sprintf("Secret/%s in namespace %s", sopsAgeSecretName, fluxSystemNamespace)},
			Notes:  []string{"The Age private key is read from the local filesystem and applied directly to the cluster. It is not written to the GitOps repository."},
		},
		Run: func(ctx context.Context) error {
			return reconcileSopsAgeSecret(ctx, sopsKeyPath, kubeconfigPath, runner)
		},
	}
}

// reconcileSopsAgeSecret reads the local Age key file and creates (or updates)
// the sops-age Secret in the flux-system namespace via kubectl.
func reconcileSopsAgeSecret(ctx context.Context, sopsKeyPath, kubeconfigPath string, runner lifecycleCommandRunner) error {
	sopsKeyPath = strings.TrimSpace(sopsKeyPath)
	if sopsKeyPath == "" {
		return fmt.Errorf("SOPS Age key path is empty; run opencenter cluster init to generate the key")
	}

	keyData, err := os.ReadFile(sopsKeyPath)
	if err != nil {
		return fmt.Errorf("read SOPS Age key from %s: %w (run opencenter cluster init to generate the key)", sopsKeyPath, err)
	}
	if len(strings.TrimSpace(string(keyData))) == 0 {
		return fmt.Errorf("SOPS Age key file %s is empty", sopsKeyPath)
	}

	// Write the key to a temporary file for kubectl --from-file.
	tempDir, err := os.MkdirTemp("", "opencenter-sops-age-secret-")
	if err != nil {
		return fmt.Errorf("create temporary directory for sops-age Secret: %w", err)
	}
	defer os.RemoveAll(tempDir)
	if err := os.Chmod(tempDir, 0o700); err != nil {
		return fmt.Errorf("secure temporary directory for sops-age Secret: %w", err)
	}

	keyFilePath := filepath.Join(tempDir, "age.agekey")
	if err := os.WriteFile(keyFilePath, keyData, 0o600); err != nil {
		return fmt.Errorf("write temporary Age key file: %w", err)
	}

	// Generate the Secret manifest via dry-run.
	createArgs := []string{
		"--kubeconfig", kubeconfigPath,
		"-n", fluxSystemNamespace,
		"create", "secret", "generic", sopsAgeSecretName,
		"--from-file=" + sopsAgeSecretKey + "=" + keyFilePath,
		"--dry-run=client", "-o", "yaml",
	}
	manifest, err := runner.Run(ctx, "", nil, "kubectl", createArgs...)
	if err != nil {
		return fmt.Errorf("build %s Secret manifest: %w", sopsAgeSecretName, err)
	}

	manifestPath := filepath.Join(tempDir, "secret.yaml")
	if err := os.WriteFile(manifestPath, manifest, 0o600); err != nil {
		return fmt.Errorf("write temporary %s Secret manifest: %w", sopsAgeSecretName, err)
	}

	// Apply the Secret to the cluster.
	if _, err := runner.Run(ctx, "", nil, "kubectl", "--kubeconfig", kubeconfigPath, "apply", "-f", manifestPath); err != nil {
		return fmt.Errorf("apply %s Secret: %w", sopsAgeSecretName, err)
	}

	return nil
}
